server:
  port: ${port:8080}
  shutdown: graceful

spring:
  application:
    name: application-processing-system

  #Database
  liquibase:
    enabled: true
    change-log: classpath:db/changelog.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/applications_db
    username:
    password:
  hikari:
    maximum-pool-size: 20
    connectionTimeout: 40000
    idleTimeout: 600000
    maxLifetime: 1800000
  jpa:
    properties:
      hibernate:
        show_sql: true
        generate_ddl: false
        ddl_auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_inserts: true
        order_updates: true
        flush-mode: manual
        jdbc:
          batch_size: 500

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true